-- Clear existing data
DELETE FROM trip_recommendations;
DELETE FROM itineraries;
DELETE FROM destinations;

-- Insert destinations
INSERT INTO destinations (name, location, description, weather, attractions, avg_budget) VALUES
('Bali', 'Indonesia', 'Tropical paradise with beautiful beaches and rich culture', 'Tropical, 25-32°C year-round', 'Uluwatu Temple, Rice Terraces, Nusa Dua Beach', 1500),
('Paris', 'France', 'City of lights and romance', 'Temperate, 5-25°C seasonal variation', 'Eiffel Tower, Louvre Museum, Notre-Dame Cathedral', 2000),
('Tokyo', 'Japan', 'Modern metropolis with traditional charm', 'Four seasons, 5-30°C seasonal variation', 'Shibuya Crossing, Mount Fuji, Senso-ji Temple', 2500),
('Machu Picchu', 'Peru', 'Ancient Incan citadel in the Andes', 'Highland climate, 10-20°C', 'Incan ruins, Huayna Picchu, Sun Gate', 1800),
('Dubai', 'UAE', 'Modern luxury in the desert', 'Desert climate, 20-40°C', 'Burj Khalifa, Palm Jumeirah, Dubai Mall', 3000),
('Santorini', 'Greece', 'Stunning island with white-washed buildings and sunsets', 'Mediterranean, 15-28°C', 'Oia Village, Volcanic Beaches, Ancient Thira', 2200),
('New York City', 'USA', 'The city that never sleeps', 'Four seasons, -5-30°C', 'Times Square, Central Park, Statue of Liberty', 2800),
('Maldives', 'Maldives', 'Paradise of overwater bungalows and marine life', 'Tropical, 24-31°C', 'Coral Reefs, Water Villas, Marine Life', 3500),
('Kyoto', 'Japan', 'Ancient capital with stunning temples and gardens', 'Four seasons, 4-32°C', 'Fushimi Inari Shrine, Arashiyama Bamboo Grove', 2000),
('Barcelona', 'Spain', 'Artistic city with unique architecture', 'Mediterranean, 10-28°C', 'Sagrada Familia, Park Güell, Las Ramblas', 1800);

-- Insert trip recommendations
INSERT INTO trip_recommendations (destination_id, trip_type, suitable_for, estimated_budget, recommended_duration, 
    rating, best_time_to_visit, weather_conditions, highlights, travel_tips, local_events, created_date, last_updated) VALUES
(1, 'BEACH_HOLIDAY', 'COUPLES', 1500, 7, 4.8, 'April to October', 'Tropical, dry season',
    'Sunset at Uluwatu, Ubud Monkey Forest, Besakih Temple', 
    'Rent a scooter, carry sunscreen, respect local customs',
    'Galungan Festival, Kuningan Festival',
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'CULTURAL', 'FAMILY', 2000, 5, 4.7, 'March to May', 'Mild spring weather',
    'Eiffel Tower light show, Seine River cruise, Louvre guided tour',
    'Buy museum pass, learn basic French phrases, use Metro',
    'French Open, Bastille Day celebrations',
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'URBAN_ADVENTURE', 'FRIENDS', 2500, 6, 4.9, 'March to April', 'Cherry blossom season',
    'Robot Restaurant, Tsukiji Market, Harajuku fashion district',
    'Get a rail pass, try local food, book hotels early',
    'Cherry Blossom Festival, Sumo Tournament',
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'ADVENTURE', 'SOLO', 1800, 4, 4.6, 'May to October', 'Dry season, mild temperatures',
    'Sunrise at Machu Picchu, Inca Trail, Sacred Valley',
    'Altitude acclimation, book permits early, bring hiking gear',
    'Inti Raymi Festival, Fiestas del Cusco',
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'LUXURY', 'COUPLES', 3000, 5, 4.8, 'November to March', 'Pleasant winter weather',
    'Desert safari, Burj Khalifa observation deck, Gold Souk',
    'Book desert safari in advance, respect local dress code, visit during winter',
    'Dubai Shopping Festival, Dubai Food Festival',
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'ROMANTIC', 'COUPLES', 2200, 6, 4.9, 'June to September', 'Warm and sunny',
    'Sunset in Oia, Wine tasting, Volcanic beach tour',
    'Book caldera view hotels early, rent ATV for island exploration',
    'Santorini International Film Festival, Wine Festival',
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'CITY_BREAK', 'FRIENDS', 2800, 5, 4.7, 'April to June', 'Mild spring weather',
    'Broadway shows, Museum hopping, High Line walk',
    'Get CityPASS, use subway, book shows in advance',
    'NYC Restaurant Week, Shakespeare in the Park',
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 'LUXURY', 'HONEYMOON', 3500, 8, 5.0, 'December to April', 'Dry season, perfect weather',
    'Snorkeling with manta rays, Sunset cruise, Island hopping',
    'Book water villa, arrange seaplane transfers, pack reef-safe sunscreen',
    'Underwater Festival, Cultural performances',
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 'CULTURAL', 'SOLO', 2000, 5, 4.8, 'March to May', 'Cherry blossom season',
    'Temple visits, Tea ceremony, Garden tours',
    'Get temple pass, try local ryokan, rent bicycle',
    'Cherry Blossom Festival, Gion Festival',
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 'URBAN_ADVENTURE', 'FAMILY', 1800, 4, 4.6, 'May to July', 'Warm Mediterranean weather',
    'Gaudi architecture tour, Cooking classes, Beach day',
    'Book Sagrada Familia tickets online, watch for pickpockets',
    'La Mercè Festival, Music festivals',
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert sample itineraries
INSERT INTO itineraries (destination_id, title, description, start_date, end_date, total_budget, travel_mode, preferences)
VALUES 
(1, 'Romantic Bali Getaway', 'A week of romance and adventure in Bali', 
    '2024-06-15', '2024-06-22', 1500, 'FLIGHT', 'Beachfront resorts, couple activities'),
(2, 'Paris Family Adventure', 'Exploring Paris with the family', 
    '2024-07-01', '2024-07-06', 2000, 'TRAIN', 'Kid-friendly activities, central location'),
(3, 'Tokyo Tech Tour', 'Exploring modern Japan with friends', 
    '2024-04-01', '2024-04-07', 2500, 'FLIGHT', 'Technology focus, local cuisine'),
(4, 'Machu Picchu Trek', 'Solo adventure to the ancient Incan ruins', 
    '2024-05-15', '2024-05-20', 1800, 'FLIGHT', 'Adventure activities, historical sites'),
(5, 'Dubai Luxury Escape', 'Luxury shopping and desert adventures', 
    '2024-11-20', '2024-11-25', 3000, 'FLIGHT', 'Luxury hotels, fine dining'),
(6, 'Greek Island Romance', 'Romantic getaway in Santorini', 
    '2024-06-10', '2024-06-16', 2200, 'FLIGHT', 'Caldera views, wine tasting'),
(7, 'NYC City Explorer', 'Big Apple adventure with friends', 
    '2024-05-01', '2024-05-06', 2800, 'FLIGHT', 'Broadway shows, rooftop bars'),
(8, 'Maldives Paradise', 'Luxury honeymoon in paradise', 
    '2024-12-10', '2024-12-18', 3500, 'FLIGHT', 'Overwater villa, spa treatments'),
(9, 'Kyoto Cultural Journey', 'Solo exploration of Japanese culture', 
    '2024-04-05', '2024-04-10', 2000, 'TRAIN', 'Temple visits, traditional experiences'),
(10, 'Barcelona Family Fun', 'Family adventure in Catalunya', 
    '2024-06-20', '2024-06-24', 1800, 'FLIGHT', 'Family-friendly tours, beach time'); 